[platformio]
src_dir = palnagotchi

[env:esp32]
platform = espressif32
framework = arduino
board = m5stack-atom
monitor_speed = 115200
board_build.partitions = no_ota.csv
lib_deps =
  m5stack/M5Unified
  bblanchon/ArduinoJson
  h2zero/NimBLE-Arduino
